### ISSUE TITLE
Anchors before a new section should replace the implicit section ID

### ISSUE THREAD

**Issue by wouterj** [phpDocumentor/guides#307]
Consider this rst document:

```rst
Section A
---------

.. _custom-id:

Section B
---------
```

It should contain 2 sections: Section A with (implicit) id `section-a` and Section B with (explicit) id `custom-id`.
Currently, this library adds an `<a name="custom-id"></a>` in front of Section B, but still keeps its implicit ID (`section-b`).

We should "collapse" an `AnchorNode` if it's directly followed by a `SectionNode` using a compiler pass (#221 implemented a similar logic for the `.. class::` directive).

**Comment by linawolf** [comment]
We solved this for the doctrine/rst-parser and should move the solution (if applicable) and the tests here

**Comment by linawolf** [comment]
@wouterj do the tests in this PR cover what you need once they are solved?

https://github.com/phpDocumentor/guides/pull/308

**Comment by wouterj** [comment]
Yes, thanks for adding them!

**Comment by jaapio** [comment]
I'm going to try to summarize what I learned about references in RST... this is going to be a long story... as it is slightly complicated. But also diverse between standards...

We know 2 types of elements that can be used to create links. Doc utils names them as implicit and explicit hyperlink targets.
Implicit targets are elements that you can link to because of there type. Docutils has the following elements that may define implicite targets. titles footnotes citations

Explicit targets are the ones that we define as .. _target: optional followed by a link or other target.

To avoid conflicts  implicit links are overwritten by explicit ones... so in this construct:
```
.. _my-reference-label:

Section to cross-reference
--------------------------

This is the text of the section.

It refers to the section itself, see :ref:`my-reference-label`.
```
Without the explicit section we would have a link id with:
section-to-cross-reference

It is unclear to me, but not unexpected a link Section to cross-reference could work. However docutils does not specify the normalization of implicit link targets..

With the explicit .. _my-reference-label:  the implicit target is removed, according to the sphinx documentation. https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-ref

Multiple explicit link targets are allowed above those elements.
in html this will result into replacing the id of a title with the explicit link id. When multiple links are added, multiple anchors are added? (need to check this with sphinx)

---

Right now our implementation supports (with bugs) the text roles ref and doc the latter seems to be implemented invalid.... Docs should resolve to documents, and not to sections, it is some how supported by the implementation to link to sections. According to sphinx doc should only be used to link documents, not sections.

ref should be the solution to link to explicit link targets and implicit targets. We could see the short notation
`Section title`_
which should only work in a single document as a overall solution to alias of ref  this will make us different from the sphinx standard and docutils... but will improve the user experience? As it feels a bit odd to have 3 solutions to have a different type of links, which should do the same think?

**Comment by linawolf** [comment]
You have to consider also the link titles. When a reference is made without explicit title the title of the target is used. This is only possible if the target has a title which is when the the reference is targeted at a title or figure with caption.

**Comment by wouterj** [comment]
I've set up a small test Sphinx project: https://wouterj.nl/sphinx-tests/ (source: https://github.com/wouterj/sphinx-tests/tree/references/docs )

To summarize:

* ``:ref:`some-section` `` can only be used to reference explicit references (across the project)
* `` `Some section`_`` can only be used to reference implicit references (which by definition only work for the current document)
* ``:doc:`some_document` `` can only be used to reference documents, not sections

And as for the link titles, like mentioned by Lina, they are auto-generated for sections (the first title) and figures (the first paragraph of the figure caption) and the link is rendered invalid when linking to other elements without providing the title (like paragraphs).

I've seen all of these types of references/links used in the Symfony docs, so I would like to support all of it in this library (and happy to help with this).

**Comment by wouterj** [comment]
What is interesting btw is that the test project proves this issue invalid, as Sphinx keeps using the old ID and only adds an anchor for the explicit reference: https://github.com/wouterj/sphinx-tests/blob/references/out/index.html#L56-57

**Comment by jaapio** [comment]
Thanks for your sphinx test repo, I will add some tests that we skip for now to ensure this behavior will be covered

**Comment by linawolf** [comment]
solved by https://github.com/phpDocumentor/guides/pull/371
